name: CI Pipeline

on:
  pull_request:
    types: [closed]
    

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
      - run: npm cache clean --force
      - run: npm install
      - run: npm install prop-types
      - run: npm install react react-dom
      - run: npm install --save-dev @babel/cli
      - run: npm install --save-dev @testing-library/jest-dom
      - run: npm install --save-dev jest-environment-jsdom
      - run: npm install --save-dev eslint @babel/eslint-parser
      - run: npm install --save-dev identity-obj-proxy
      - run: npm install eslint-config-react-app --save-dev
      - run: npm install --save-dev jest @babel/core @babel/preset-env babel-jest
      - run: npm install --save-dev @babel/preset-react
      - run: npm run lint
      - run: npm run prettier --write
      - run: npm install --save-dev @testing-library/react
      - run: CI=true npm run test
      - run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Assume Role
        run: |
          aws sts assume-role --role-arn ${{ secrets.ARN_AWS }} --role-session-name SessionName --duration-seconds 3600 > /tmp/credentials && \
      
      - name: Connect to EC2 Instance
        run: |
          aws ec2 ssh --instance-ids i-07151c021accf6335 --key-name --key-name $K8S_HOST && \ whoami
